config/routes.rb
Rails.application.routes.draw do
  get 'reports/penguin'
  get 'reports/best_in_cafe_2014'

  resources :notices
  resources :posts do
    collection do
      get 'best'
    end
  end

  resources :videos do
    collection do
      get 'best'
    end
  end
  resources :shops
  resources :items

  scope '/admin' do
    get 'videos' => 'videos#admin', as: :admin_videos
    get 'posts' => 'posts#admin', as: :admin_posts
    get 'items' => 'items#admin', as: :admin_items
    get 'shops' => 'shops#admin', as: :admin_shops
    get 'notices' => 'notices#admin', as: :admin_notices
  end

  root 'videos#best'

  get 'discussion' => 'static_pages#discussion', as: :discuss
  get 'pop' => 'static_pages#popular'
  get 'resources' => 'static_pages#resources'
  get 'home' => 'static_pages#home'

  get 'admin' => 'static_pages#admin'

  get 'posts/category/:category/'  => 'posts#index', as: :category_posts
  get 'video/category/:category/'  => 'videos#index', as: :category_videos
  get 'video/selected/'  => 'videos#index', as: :selected_videos
  get 'posts/category/:category/'  => 'posts#index', as: :cafe_category_posts

end

app/controllers/static_pages_controller.rb
# encoding: utf-8
class StaticPagesController < ApplicationController

  def home
    #@shops = Shop.order_by_update.first(4)
    @items = Item.order_by_date.to_a.uniq {|p| p.shop_id}[0..7]
    @videos = Video.order_by_date.first(4)
    @posts = Post.order_by_date.first(3)
  end

  def discussion
  end

  def nodes
    @nodes = RESOURCES_CONSTANT::NODES
  end

  def selected
  end

  def mobile
    @shops = Shop.order_by_update.first(4)
    @videos = Video.order_by_date.first(4)
    @posts = Post.order_by_date.first(3)
  end

  def popular
    base_videos = Video.by_source('youtube')
    base_posts = Post.by_forum('cafe')
    if !(params[:number] or params[:sort])
      params[:sort] = 'new'
    end
    if  params[:number]
      number = params[:number].to_i
      trending_videos = base_videos.created_in_days(number).order_by_rating.first(4)
      @videos =  trending_videos
      @posts =  base_posts.created_in_days(number).order_by_likes.first(5)
    elsif params[:sort] == 'new'
      @videos = base_videos.order(created_at: :desc).first(4)
      @posts = base_posts.order(created_at: :desc).first(5)
    end
  end

  def admin

  end

  def resources
    @community_websites = RESOURCES_CONSTANT::GENERAL_WEBSITES[0]
    @general_websites = RESOURCES_CONSTANT::GENERAL_WEBSITES[1]

    @oversea_shops = RESOURCES_CONSTANT::OVERSEA_SHOPS

    @youtube_channels = []
    RESOURCES_CONSTANT::YOUTUBE_CHANNELS.first(4).each do |key, value|
      @youtube_channels = @youtube_channels.push(value)
    end


  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_site.html.erb
<div class="col-md-3 site">
  <% if !site[:favicon].blank?  %>
    <%= image_tag(site[:favicon], class: 'favicon') %>
  <% end  %>
  <%= link_to(site[:name].truncate(23), site[:url], class: "title #{'placeholder' if site[:favicon].blank?}") %>
</div>

app/views/static_pages/admin.erb
<h2>Admin Dashboard</h2>

<%= link_to 'videos', admin_videos_path %>
<%= link_to 'posts', admin_posts_path %>
<%= link_to 'items', items_path %>
<%= link_to 'shops', admin_shops_path %>
<%= link_to 'notice', admin_notices_path %>

app/views/static_pages/cafe_spot.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <h4 class="no-margin">Order by</h4>
      <%= link_to 'Time', sort: 'date' %>
      <%= link_to 'Likes', sort: 'like' %>
      <br>
      <%= cafe_tag_nav_link('post', 'new') %>
      <%= cafe_tag_nav_link('post', 'card') %>
      <%= cafe_tag_nav_link('post', 'mental') %>
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr class="no-style-link">
        <th ><h2 class="no-margin">
              <%= link_to cafe_spot_path do %><strong>Cafe Digest</strong>
              <% end  %>
        </h2></th>
        <th><%= link_to '❤', sort: 'like' %></th>
        <th><%= link_to 'Time', sort: 'date' %></th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
              <%= link_to post.title, post.url %> - <%= cafe_tag_link post %><br>
            <%= link_to post.url, class:'no-style-link' do %>
              <%= truncate(post.abstraction, length: 250)%>
            <% end %>
          </td>
          <td><%= post.likes %></td>
          <td><%= post.created_at.strftime("%m/%d") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/static_pages/discussion.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'magicdigest'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    

app/views/static_pages/home.html.erb
<div class="panel panel-default main">
  <div class="panel-heading clearfix">
    <div class="pull-right">
      <a class="more-items-control" data-no-turbolink href="#"><span class="glyphicon glyphicon-chevron-down"></span> 展开</a>
      <%= link_to('更多', shops_path) %>
    </div>
    <h2 class="panel-title"><strong>最新产品</strong></h2>
  </div>
  <div class="panel-body">
    <div class="items">
      <!--<h3>Items</h3>-->
      <div class="row">
        <% @items[0..3].each do |item| %>
          <%= render partial: 'items/item', locals: {item: item} %>
        <% end  %>
        <div id="more-items" style="display: none">
          <% @items[4..7].each do |item| %>
            <%= render partial: 'items/item', locals: {item: item} %>
          <% end  %>
          <a class="more-items-control toggle-control pull-right" data-no-turbolink href="#"><strong><span class="glyphicon glyphicon-chevron-up"></span>收起</strong></a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default main">
  <div class="panel-heading clearfix">
    <%= link_to('更多', videos_path, class: 'pull-right') %>
    <h2 class="panel-title"><strong>视频</strong></h2>
  </div>
  <div class="panel-body">
    <div class="videos">
      <div class="row">
        <% @videos.each do |item| %>
          <%= render partial: 'videos/video', locals: {item: item, show_views: false}  %>
        <% end  %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default main">
  <div class="panel-heading clearfix">
    <div class="pull-right">
      <%= link_to('更多', posts_path, class: 'pull-right') %>
    </div>

    <h2 class="panel-title"><strong>论坛热帖</strong></h2>
  </div>
  <div class="panel-body">
    <div class="posts">
      <div class="row">
        <% @posts.each do |item| %>
          <%= render partial: 'posts/post', locals: {item: item}  %>
        <% end  %>
      </div>
    </div>
  </div>
</div>





app/views/static_pages/mobile.html.erb
<section>
  <nav>
    <h5>Videos</h5>
  </nav>
  <div class="videos-content">
    <% @videos.each do |video|  %>
    <div class="video row">
      <div class="col-xs-4">
        <%= link_to video.url do %>
          <%= image_tag(video.img_url, class: 'img-responsive') %>
        <% end %>
      </div>
      <div class="col-xs-8">
        <%= link_to video.title, video.url %>
        <span class="pull-right"><%= video.created_at.strftime("%m/%d") %></span>
      </div>
    </div>
      <% end %>
  </div>
</section>

app/views/static_pages/nodes.html.erb
<div class="row">
  <div class="col-md-6">
    <% @nodes.each_with_index do |node,index|  %>
      <div class="panel panel-default main">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" href=".node-<%= index %>">
              <%= node[:title] %>
            </a>
          </h4>
        </div>
        <div class="panel-body">
          <span class="intro collapse in node-<%= index %>"><%= node[:intro] %></span>
          <div class="content collapse node-<%= index %>">
            <%= simple_format node[:content] %>
          </div>
        </div>
      </div>
    <% end %>


  </div>
</div>


app/views/static_pages/popular.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <h4 class="no-margin">Trending in</h4>
      <div class="selectors">
        <%= selector_link('Now', sort: 'new') %>
        <%= selector_link('7 Days', number: '7') %>
        <%= selector_link('30 Days', number: '30' ) %>
        <%= selector_link('90 Days', number: '90' ) %>
      </div>
    </div>
  </div>

  <%= render 'layouts/new_video' %>
<% end %>

<div class="main panel panel-default">
  <div class="panel-body no-bottom-space">
    <h3 class="no-margin no-style-link">
      <%= link_to videos_path do %>
      <span class="glyphicon glyphicon-facetime-video"></span>
      <strong>Videos</strong>
      <% end %>
    </h3>
    <div class="videos row">
      <% @videos.each do |item| %>
        <%= render partial: 'videos/video', locals: {item: item}  %>
      <% end  %>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped table-condensed">
      <thead>
      <tr class="no-style-link">
        <th ><h3 class="no-margin">
          <%= link_to posts_path do %>
            <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>
            <strong>Cafe Posts</strong>
          <% end  %>
        </h3></th>
        <th class="hidden-xxs">❤</th>
        <th class="hidden-xxs">Time</th>
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
        <%= render partial: 'posts/post_row', locals: {post: post}  %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>



app/views/static_pages/resources.html.erb
<div class="resources">

  <div class="panel panel-default main">
    <div class="panel-heading clearfix">
      <h2 class="panel-title"><span class="glyphicon glyphicon-star"></span> General</h2>
    </div>
    <div class="panel-body">
      <div class="row">
        <% @community_websites[:sites].each do |site|  %>
          <%= render partial: 'site', locals: {site: site} %>
        <% end  %>
      </div>
      <div class="row">
      <% @general_websites[:sites].each do |site|  %>
        <%= render partial: 'site', locals: {site: site} %>
      <% end  %>
      </div>
    </div>
  </div>

  <div class="panel panel-default main">
    <div class="panel-heading clearfix">
      <h2 class="panel-title"><span class="glyphicon glyphicon-shopping-cart"></span> Shops</h2>
    </div>
    <div class="panel-body">
      <div class="row">
        <% @oversea_shops.each do |site|  %>
          <%= render partial: 'site', locals: {site: site} %>
        <% end  %>
      </div>
    </div>
  </div>

  <div class="panel panel-default main">
    <div class="panel-heading clearfix">
      <h2 class="panel-title">
        <span class="glyphicon glyphicon-facetime-video"></span>
        Youtube</h2>
    </div>
    <ul class="list-group">
      <%# @youtube_channels.count %>
      <% @youtube_channels.each do |channel_group|  %>
      <li class="list-group-item">
        <div class="row">
          <% channel_group.each do |site|  %>
            <div class="col-md-3 site">
              <%= image_tag(site[:favicon], class: 'favicon') %>
              <%= link_to(site[:name].truncate(25), site[:url], class: 'title') %>
            </div>
          <% end  %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

</div>


app/views/static_pages/selected.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to 'All Videos', videos_path %>
    </div>
  </div>
<% end %>

<h2>Today's pick </h2>
<div class="videos row">
  <% @random_videos.each do |video|  %>
    <%= render partial: 'videos/video', locals: {item: video}  %>
  <% end  %>
</div>

<% @monthly_videos.reverse.each_with_index do |video_group, index| %>
  <% if video_group.any?  %>
    <h2>Best in <%= video_group.first.created_at.strftime("%Y/%m") %> </h2>
    <div class="videos row">
      <% video_group.each do |item| %>
        <%= render partial: 'videos/video', locals: {item: item}  %>
      <% end  %>
    </div>
  <% end  %>
<% end  %>


<%#= will_paginate @videos, renderer: BootstrapPagination::Rails %>