config/routes.rb
Rails.application.routes.draw do
  get 'reports/penguin'
  get 'reports/best_in_cafe_2014'

  resources :notices
  resources :posts do
    collection do
      get 'best'
    end
  end

  resources :videos do
    collection do
      get 'best'
    end
  end
  resources :shops
  resources :items

  scope '/admin' do
    get 'videos' => 'videos#admin', as: :admin_videos
    get 'posts' => 'posts#admin', as: :admin_posts
    get 'items' => 'items#admin', as: :admin_items
    get 'shops' => 'shops#admin', as: :admin_shops
    get 'notices' => 'notices#admin', as: :admin_notices
  end

  root 'videos#best'

  get 'discussion' => 'static_pages#discussion', as: :discuss
  get 'pop' => 'static_pages#popular'
  get 'resources' => 'static_pages#resources'
  get 'home' => 'static_pages#home'

  get 'admin' => 'static_pages#admin'

  get 'posts/category/:category/'  => 'posts#index', as: :category_posts
  get 'video/category/:category/'  => 'videos#index', as: :category_videos
  get 'video/selected/'  => 'videos#index', as: :selected_videos
  get 'posts/category/:category/'  => 'posts#index', as: :cafe_category_posts

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :items, dependent: :destroy
  validates :url, uniqueness: true

  scope :order_by_update, -> {order('updated_at DESC')}

  def last_updated_at
    self.items.first.created_at
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
    @items = Item.order_by_sales.to_a.uniq {|p| p.shop_id}[0..4]
  end

  def admin
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @items = @shop.items.all
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :avatar_url, :url)
    end
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar_url %><br>
    <%= f.text_field :avatar_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/admin.html.erb
<h1>Listing shops</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>avatar</th>
    <th>url</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @shops.each do |shop| %>
    <tr>
      <td><%= link_to shop.name, shop.url %></td>
      <td><%= image_tag(shop.avatar_url) %></td>
      <td><%= shop.url %></td>
      <td><%= link_to 'Show', shop %></td>
      <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
      <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New shop', new_shop_path %>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to 'Shops', shops_path %>
      <%= link_to 'Items', items_path %>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><%= link_to '正在热销', items_path, sort: 'pop' %></h4>
    </div>
    <table class="table table-condensed">
    <!--<thead>
      <tr>
        <th>#</th>
        <th colspan="2">正在热销</th>
      </tr>
    </thead>-->
    <tbody>
    <% @items.each_with_index do |item, index| %>
      <tr>
        <td><span class="badge"><%= index+1 %></span></td>
        <td><%= link_to item.title, item.url %></td>
        <td><%= item.sales_number %></td>
      </tr>
     <% end  %>
    </tbody>
    </table>
  </div>
<% end %>

<% @shops.each do |shop| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to 'http://' + shop.url do %>
      <h2 class="no-margin">
        <%= image_tag(shop.avatar_url, class: 'shop-avatar') %>
        <%= shop.name %>
        <small> - - - <%= shop.url%></small>
      </h2>
      <% end %>
    <div class="items">
      <div class="row">
        <% shop.items.order_by_date.first(4).each do |item|  %>
          <%= render partial: 'items/item', locals: {item: item, show_shop: false} %>
        <% end  %>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<div class="row">
  <h2><%= link_to @shop.name, url_with_protocol(@shop.url), :target => '_blank' %></h2>
  <div class="items">
    <% @items.each do |item|  %>
      <%= render partial: 'items/item', locals: {item: item, show_shop: false} %>
    <% end  %>
  </div>
</div>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>