config/routes.rb
Rails.application.routes.draw do
  get 'reports/penguin'
  get 'reports/best_in_cafe_2014'

  resources :notices
  resources :posts do
    collection do
      get 'best'
    end
  end

  resources :videos do
    collection do
      get 'best'
    end
  end
  resources :shops
  resources :items

  scope '/admin' do
    get 'videos' => 'videos#admin', as: :admin_videos
    get 'posts' => 'posts#admin', as: :admin_posts
    get 'items' => 'items#admin', as: :admin_items
    get 'shops' => 'shops#admin', as: :admin_shops
    get 'notices' => 'notices#admin', as: :admin_notices
  end

  root 'videos#best'

  get 'discussion' => 'static_pages#discussion', as: :discuss
  get 'pop' => 'static_pages#popular'
  get 'resources' => 'static_pages#resources'
  get 'home' => 'static_pages#home'

  get 'admin' => 'static_pages#admin'

  get 'posts/category/:category/'  => 'posts#index', as: :category_posts
  get 'video/category/:category/'  => 'videos#index', as: :category_videos
  get 'video/selected/'  => 'videos#index', as: :selected_videos
  get 'posts/category/:category/'  => 'posts#index', as: :cafe_category_posts

end

app/models/post.rb
# encoding: UTF-8
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :url, uniqueness: true

  scope :by_forum, ->(forum) { where source: forum }
  scope :by_category, ->(category) { where category: category }
  scope :order_by_date, -> {order('created_at DESC')}
  scope :order_by_update, -> {order('updated_at DESC')}
  scope :order_by_views, -> {order('views IS NULL, views DESC')}
  scope :order_by_likes, -> { order('likes IS NULL, likes DESC') }
  scope :order_by_reply_number, -> {order('reply_number IS NULL, reply_number DESC') }
  scope :created_in_days, ->(number)  do
    filtered = where('created_at >= ?', Time.zone.now - number.days)
    if filtered.length < 4
      order(:created_at => :desc).limit(4) # takes last 4 created
    else
      filtered
    end
  end

  scope :best_of_the_month, ->(year, month) do
    time = Time.new(year, month)
    start_time = time.beginning_of_month
    end_time = time.end_of_month
    where("created_at > ? AND created_at < ?", start_time, end_time).order_by_likes
  end

  require 'open-uri'

  before_validation :get_info, on: :create

  def self.best_by_month
    date = Date.new(2013,1,1)
    monthly_posts = []
    while true
      posts = Post.best_of_the_month(date.year, date.month).first(7)
      monthly_posts << posts
      date += 1.month
      break if date > Date.today.beginning_of_month
    end
    monthly_posts
  end

  def get_info
    url = self.url
    doc = Nokogiri::HTML(open(url))
    if self.source.blank?
      get_source_and_title(doc, url)
      get_likes(doc)
    end
    if self.source == 'cafe'
      #get_cafe_author_info(doc)
      get_cafe_abstraction_and_time(doc)
      categorize_post
    elsif self.source == 'tieba'
      get_tieba_abstraction(doc)
    end
  end

  def get_source_and_title(doc, url)
    if url.include? 'themagiccafe'
      self.source = 'cafe'
      self.title=doc.css("title").text.split('The Magic Cafe Forums - ')[1]
    end
  end

  def get_cafe_author_info(doc)
    avatar = doc.at("table.normal img.nb[alt='View Profile']")['src']
    url = 'http://www.themagiccafe.com/forums/' + avatar
    author_name = doc.at("table.normal strong").text
    self.avatar = url
    self.author_name = author_name
    puts url, author_name
  end

  def categorize_post
    forum_id =  self.url.split('&forum=')[1]
    if forum_id ==  '15'
      self.category = 'mental'
    elsif forum_id ==  '2'
      self.category = 'card'
    elsif forum_id ==  '218'
      self.category = 'new'
    elsif forum_id ==  '303' || forum_id ==  '110'
      self.category = 'review'
    end
  end

  def get_cafe_abstraction_and_time(doc)
    text = doc.at("table.normal .vat.w90 .w100").text
    time = doc.at("table.normal .vat.w90 span.b").text.split('Posted: ')[1]
    text = text.split(" ").first(100).join(" ")
    self.created_at = time.to_time(:utc)
    self.abstraction = text
  end

  def get_tieba_abstraction(doc)
    text = doc.at('#j_p_postlist .d_post_content').text.split('            ')[1]
    if text
      self.abstraction = text[0..300]
    else
      puts 'no text'
    end
  end

  def get_likes_or_reply_number(doc = nil)
    doc = Nokogiri::HTML(open(self.url)) if !doc
    if self.source == 'cafe'
      self.get_likes(doc)
    elsif self.source == 'tieba'
      self.get_reply_number(doc)
    end
  end

  def get_likes(doc)
    likes = doc.at("table.normal span.midtext")
    if likes
      self.likes = likes.text.tr("^0-9", '').to_i
    else
      self.destroy
      return 'links are deleted'
    end
  end

  def get_reply_number(doc)
    reply_number = doc.at('li.l_reply_num span').text.to_i
    self.reply_number = reply_number
    puts self.reply_number
  end
end

app/controllers/posts_controller.rb
# encoding: utf-8
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    if !params[:category].blank?
      posts = Post.by_category(params[:category])
    else
      posts = Post.by_forum('cafe')
    end
    params[:sort] = 'time' if !params[:sort]
    if params[:sort] == 'like'
      posts = posts.order_by_likes
    elsif params[:sort] == 'time'
        posts = posts.order_by_date
    end
    @posts = posts.paginate(:page => params[:page], :per_page => 10)
  end

  def admin
    if params[:sort] == 'like'
      @posts = Post.order_by_likes
    elsif params[:sort] == 'reply'
      @posts = Post.order_by_reply_number
    elsif params[:sort] == 'id'
      @posts = Post.order('id DESC')
    elsif params[:sort] == 'update'
      @posts = Post.order('updated_at DESC')
    else
      @posts = Post.order_by_date
    end
  end

  def best
    @monthly_posts = Post.best_by_month.reverse.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:url, :title, :source, :category, :abstraction)
    end
end

app/helpers/posts_helper.rb
# encoding: utf-8
module PostsHelper
  def show_source_name(item)
    if item.source == 'cafe'
      'cafe'
    elsif item.source == 'tieba'
      '贴吧'
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :abstraction %><br>
    <%= f.text_field :abstraction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col-md-4">
  <div class="thumbnail">
    <div class="caption">
      <h4 class="post-title"><%= link_to item.title, item.url %>
        <small class="pull-right">
          <%= tag_link item %>
          <%= show_source_name(item) %>

          <%= item.created_at.strftime("%m/%d") %>
        </small></h4>
      <%= truncate(item.abstraction, length: 100) %>
    </div>
  </div>
</div>

app/views/posts/_post_no_table.html.erb
<div class="post col-md-12">
  <h4>
    <%= link_to item.title, item.url %>
    <%= tag_link(item) %>
    <small class="pull-right">
      <% if item.source == 'cafe' %>
        <%= item.likes %>❤
      <% elsif item.source == 'tieba' %>
        <%= item.reply_number %><span class="glyphicon glyphicon-comment"></span>
      <% end  %>
      <%= item.created_at.strftime("%m/%d") %>
      <%#= item.source %>
    </small>
  </h4>
  <div class="">
    <%= truncate(item.abstraction, length: 200) %>
  </div>
</div>

app/views/posts/_post_row.html.erb
<% unless defined?(show_number)  %>
  <% show_number = false  %>
<% end  %>

<tr>
  <% if show_number %>
  <td><%= post_number+1 %></td>
  <% end  %>
  <td>
    <%= link_to post.title, post.url %><span class="hidden-xxs"> - <%= cafe_tag_link post %></span><br>
    <%= link_to post.url, class:'no-style-link hidden-xxs' do %>
      <%= truncate(post.abstraction, length: 250)%>
    <% end %>
    <div class="visible-xxs">
      <%= cafe_tag_link post %>
      <div class="pull-right">
        ❤<%= post.likes %>
        <%= post.updated_at.strftime("%m/%d") %>
      </div>
    </div>
  </td>
  <% if show_number %>
    <td class="hidden-xxs"><%= post.reply_number %></td>
    <td class="hidden-xxs"><%="#{number_to_human(post.views, precision: 2)}" %></td>
  <% end  %>
  <td class="hidden-xxs"><%= post.likes %></td>
  <td class="hidden-xxs"><%= post.created_at.strftime("%m/%d") %></td>
  <% if !show_number %>
  <!--<td class="hidden-xxs"><%= post.updated_at.strftime("%m/%d") %></td>-->
  <% end  %>
</tr>

app/views/posts/_sidebar_selector.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul class="nav nav-pills nav-justified">
        <%= accurate_nav_link 'Best Posts', best_posts_path %>
        <%= accurate_nav_link  'All Posts', posts_path %>
      </ul>

    </div>
  </div>

  <%= yield :sidebar_selector_content %>
<% end %>

app/views/posts/admin.html.erb
<h1>Listing posts</h1>
Order by
<%= link_to 'Date', sort: 'date' %>
<%= link_to 'Update', sort: 'update' %>
<%= link_to 'Reply Number', sort: 'reply' %>
<%= link_to 'Likes', sort: 'like' %>
<%= link_to 'ID', sort: 'id' %>

<%= link_to 'New Post', new_post_path, class:'pull-right' %>

<%= link_to 'New Post', new_post_path, class:'pull-right' %>

<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Abstraction</th>
    <th>Likes</th>
    <th>Created Time</th>
    <th>Updated Time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post.url %> - <%= post.category %></td>
      <td><%= post.abstraction %></td>
      <td><%= post.likes %></td>
      <td><%= post.created_at.strftime("%m/%d") %></td>
      <td><%= post.updated_at.strftime("%m/%d") %></td>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



app/views/posts/best.html.erb
<%= render 'sidebar_selector' %>

<% @monthly_posts.each_with_index do |post_group, index| %>
  <% if post_group.any?  %>
  <div class="panel panel-default best-posts">
    <div class="panel-body">
      <table class="table table-striped table-condensed">
        <thead>
        <tr class="no-style-link">
          <th ><h2 class="no-margin">
            Best in <%= post_group.first.created_at.strftime("%Y/%m") %>
          </h2></th>
          <th class="hidden-xxs">❤</th>
          <th class="hidden-xxs">Time</th>
        </tr>
        </thead>

        <tbody>
        <% post_group.each do |post| %>
          <%= render partial: 'posts/post_row', locals: {post: post}  %>
        <% end  %>
        </tbody>
      </table>
    </div>
  </div>
  <% end  %>
<% end  %>

<%= will_paginate @monthly_posts, renderer: BootstrapPagination::Rails %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% content_for :sidebar_selector_content do %>
  <div class="panel panel-default">
    <div class="panel-body">
  <div class="selectors">
    <h4 class="no-margin">Order by</h4>
    <%= selector_link 'Time', sort: 'create' %>
    <%#= selector_link 'Reply', sort: 'update' %>
    <%= selector_link 'Likes', sort: 'like' %>
  </div>
  <%= cafe_tag_nav_link('post', 'new') %>
  <%= cafe_tag_nav_link('post', 'card') %>
  <%= cafe_tag_nav_link('post', 'mental') %>
  <%= cafe_tag_nav_link('post', 'review') %>
    </div>
  </div>
<% end %>

<%= render 'sidebar_selector' %>


<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped table-condensed">
      <thead>
      <tr class="no-style-link">
        <th ><h2 class="no-margin">
          <%= link_to posts_path do %>
            <span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>
            <strong>Popular Cafe Posts</strong>
              <% end  %>
        </h2></th>
        <th class="hidden-xxs"><%= link_to '❤', sort: 'like' %></th>
        <th class="hidden-xxs"><%= link_to 'Time', sort: 'create' %></th>
        <!--<th class="hidden-xxs"><%= link_to 'Reply', sort: 'update' %></th>-->
      </tr>
      </thead>

      <tbody>
      <% @posts.each do |post| %>
       <%= render partial: 'posts/post_row', locals: {post: post}  %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/index2.html.erb
<% content_for :sidebar_selector do %>
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Order by</h4>
      <%= link_to 'Date', sort: 'date' %>
      <%= link_to 'Reply Number', sort: 'reply' %>
      <%= link_to 'Likes', sort: 'like' %>
      <br>
      <%= tag_nav_link('post', '新品') %>
      <%= tag_nav_link('post', '花式') %>
      <%= tag_nav_link('post', '心灵') %>
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
<table class="table table-striped">
  <thead>
  <tr>
    <th><h2 class="no-margin"><strong>论坛热帖</strong></h2></th>
    <th>❤</th>
    <th><span class="glyphicon glyphicon-comment"></span></th>
    <th>Time</th>
    <th>Source</th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td>
        <%= link_to post.title, post.url %> - <%= tag_link post %><br>
        <%= truncate(post.abstraction, length: 250)%>
      </td>
      <td><%= post.likes %></td>
      <td><%= post.reply_number %></td>
      <td><%= post.created_at.strftime("%m/%d") %></td>
      <td><%= post.source %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @post.source %>
</p>

<%= @post.created_at %>
<%= @post.updated_at %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>