config/routes.rb
Rails.application.routes.draw do
  get 'reports/penguin'
  get 'reports/best_in_cafe_2014'

  resources :notices
  resources :posts do
    collection do
      get 'best'
    end
  end

  resources :videos do
    collection do
      get 'best'
    end
  end
  resources :shops
  resources :items

  scope '/admin' do
    get 'videos' => 'videos#admin', as: :admin_videos
    get 'posts' => 'posts#admin', as: :admin_posts
    get 'items' => 'items#admin', as: :admin_items
    get 'shops' => 'shops#admin', as: :admin_shops
    get 'notices' => 'notices#admin', as: :admin_notices
  end

  root 'videos#best'

  get 'discussion' => 'static_pages#discussion', as: :discuss
  get 'pop' => 'static_pages#popular'
  get 'resources' => 'static_pages#resources'
  get 'home' => 'static_pages#home'

  get 'admin' => 'static_pages#admin'

  get 'posts/category/:category/'  => 'posts#index', as: :category_posts
  get 'video/category/:category/'  => 'videos#index', as: :category_videos
  get 'video/selected/'  => 'videos#index', as: :selected_videos
  get 'posts/category/:category/'  => 'posts#index', as: :cafe_category_posts

end

app/views/layouts/_CN_header.html.erb

<header class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <strong>魔法盒子</strong>
      <% end  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_link '最新', root_path %>
        <%= nav_link  '热门', pop_path %>
        <%#= nav_link  '精选', selected_path %>
        <%= nav_link  '淘宝', shops_path %>
        <%= nav_link  '视频', videos_path %>
        <%= nav_link  '热帖', posts_path %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= nav_link  '信息来源', resources_path, 'important-link' %>
        <%= nav_link  '留言！', discussion_path %>
<!--        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</header>

app/views/layouts/_header.html.erb

<header class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <strong>Magic Digest</strong>
      <% end  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <%= nav_link  'Trending', pop_path, nil, "glyphicon glyphicon-signal" %>
        <%= nav_link  'Videos', best_videos_path, nil,"glyphicon glyphicon-facetime-video"  %>
        <%= nav_link  'Posts', best_posts_path,nil, 'glyphicon glyphicon-cutlery' %>
        <%= nav_link  'Websites', resources_path, nil, 'glyphicon glyphicon-list-alt' %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= nav_link  'Top Penguin Live?', reports_penguin_path, 'important-link' %>
        <%= nav_link  'Discuss', discuss_path, nil, 'glyphicon glyphicon-pencil' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</header>

app/views/layouts/_new_video.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to 'Recommend a Video', new_video_path, class: 'btn btn-success btn-block' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magic Digest - Less but better</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-48003175-3', 'auto');
    ga('send', 'pageview');
  </script>
  <% end %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <div class="row">
    <div class="col-md-9">
      <% if flash[:notice] %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= flash[:notice] %>
        </div>
       <% end  %>
      <%= yield %>
    </div>
    <div class="col-md-3">
      <div class="">
        <%= yield :sidebar_selector %>
        <div class="panel panel-default main">
          <div class="panel-heading clearfix">
            <h2 class="panel-title">Websites</h2>
          </div>
          <ul class="list-group">
            <li class="list-group-item">
              <div class="row">
                <% @oversea_websites.each do |site|  %>
                  <div class="col-md-8 site">
                    <% if !site[:favicon].blank?  %>
                      <%= image_tag(site[:favicon], class: 'favicon') %>
                    <% end  %>
                    <%= link_to(site[:name], site[:url]) %>
                  </div>
                <% end  %>
              </div>
            </li>
          </ul>
        </div>
        <div class="notices">
          <div class="panel panel-default">
            <!--<div class="panel-heading">-->
              <!--<h4 class="panel-title">Notice</h4>-->
            <!--</div>-->
            <ul class="list-group">
              <li class="list-group-item notice">If you have any <strong>suggestion</strong>, you can put it <%= link_to 'Here', discuss_path %>, or contact me by 38306608@qq.com
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application2.html.erb
<!--
<!DOCTYPE html>
<html>
<head>
  <title>魔法盒子 —— 魔术，正在发生</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F5f94c3a160e0e65368c50729114616e3' type='text/javascript'%3E%3C/script%3E"));
  </script>
</head>
<body>
<%= render 'layouts/magic_digest_header' %>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <%= yield %>
    </div>
    <div class="col-md-3">
      <%= yield :sidebar_selector %>
      <%= render 'notices/notice_board' %>
    </div>
  </div>
</div>
</body>
</html>
-->